# Generated by Django 4.2.6 on 2023-10-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ссылка на видео'),
        ),
    ]
