# Generated by Django 4.2.6 on 2023-11-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_alter_lesson_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateTimeField(verbose_name='дата оплаты')),
                ('pay_amount', models.IntegerField(verbose_name='сумма оплаты')),
                ('payment_method', models.CharField(blank=True, choices=[('Оплата наличными', 'Оплата наличными'), ('Оплата картой', 'Оплата картой')], max_length=70, null=True, verbose_name='способ оплаты')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cours.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cours.lesson')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
            },
        ),
    ]
