# Generated by Django 4.2.6 on 2023-11-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_subscription_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribe',
            field=models.BooleanField(default=True, verbose_name='подписка'),
        ),
    ]
